# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        uploads_articles_adapter:
            local:
                location: '%kernel.project_dir%/public/%article_uploads%'
    filesystems:
        uploads_articles:
            adapter: uploads_articles_adapter

