twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
        - bootstrap_4_layout.html.twig

    paths:
        'assets/css': css

when@test:
    twig:
        strict_variables: true
